In [3]:
import pandas as pd
df1 = pd.read_csv('/Users/nuthakki/Downloads/TEDS-A-2011-DS0001-bndl-data-tsv/TEDS-A-2011-DS0001-data/TEDS-A-2011-DS0001-data-excel.tsv',sep = '\t')
df1.head(3)

,CASEID,YEAR,AGE,GENDER,RACE,ETHNIC,MARSTAT,EDUC,EMPLOY,DETNLF,...,BARBFLG,SEDHPFLG,INHFLG,OTCFLG,OTHERFLG,ALCDRUG,DSMCRIT,PSYPROB,HLTHINS,PRIMPAY
0,1,2011,10,2,5,5,2,4,1,-9,...,0,0,0,0,0,3,-9,-9,-9,-9
1,2,2011,7,2,5,5,3,3,1,-9,...,0,0,0,0,0,2,7,2,2,4
2,3,2011,6,1,5,5,1,3,1,-9,...,0,0,0,0,0,2,5,2,-9,-9

In [4]:
df1.columns

Index(['CASEID', 'YEAR', 'AGE', 'GENDER', 'RACE', 'ETHNIC', 'MARSTAT', 'EDUC',
       'EMPLOY', 'DETNLF', 'PREG', 'VET', 'LIVARAG', 'PRIMINC', 'ARRESTS',
       'STFIPS', 'CBSA', 'PMSA', 'REGION', 'DIVISION', 'SERVSETA', 'METHUSE',
       'DAYWAIT', 'PSOURCE', 'DETCRIM', 'NOPRIOR', 'SUB1', 'ROUTE1', 'FREQ1',
       'FRSTUSE1', 'SUB2', 'ROUTE2', 'FREQ2', 'FRSTUSE2', 'SUB3', 'ROUTE3',
       'FREQ3', 'FRSTUSE3', 'NUMSUBS', 'IDU', 'ALCFLG', 'COKEFLG', 'MARFLG',
       'HERFLG', 'METHFLG', 'OPSYNFLG', 'PCPFLG', 'HALLFLG', 'MTHAMFLG',
       'AMPHFLG', 'STIMFLG', 'BENZFLG', 'TRNQFLG', 'BARBFLG', 'SEDHPFLG',
       'INHFLG', 'OTCFLG', 'OTHERFLG', 'ALCDRUG', 'DSMCRIT', 'PSYPROB',
       'HLTHINS', 'PRIMPAY'],
      dtype='object')

In [5]:
#Get all the column names with their indexes
a = df1.columns.values
s = 0
for i in a:
    print (s, i)
    s += 1

0 CASEID
1 YEAR
2 AGE
3 GENDER
4 RACE
5 ETHNIC
6 MARSTAT
7 EDUC
8 EMPLOY
9 DETNLF
10 PREG
11 VET
12 LIVARAG
13 PRIMINC
14 ARRESTS
15 STFIPS
16 CBSA
17 PMSA
18 REGION
19 DIVISION
20 SERVSETA
21 METHUSE
22 DAYWAIT
23 PSOURCE
24 DETCRIM
25 NOPRIOR
26 SUB1
27 ROUTE1
28 FREQ1
29 FRSTUSE1
30 SUB2
31 ROUTE2
32 FREQ2
33 FRSTUSE2
34 SUB3
35 ROUTE3
36 FREQ3
37 FRSTUSE3
38 NUMSUBS
39 IDU
40 ALCFLG
41 COKEFLG
42 MARFLG
43 HERFLG
44 METHFLG
45 OPSYNFLG
46 PCPFLG
47 HALLFLG
48 MTHAMFLG
49 AMPHFLG
50 STIMFLG
51 BENZFLG
52 TRNQFLG
53 BARBFLG
54 SEDHPFLG
55 INHFLG
56 OTCFLG
57 OTHERFLG
58 ALCDRUG
59 DSMCRIT
60 PSYPROB
61 HLTHINS
62 PRIMPAY

In [6]:
#Drop unnecessary columns
df21 = df1.drop(df1.columns[[17]], axis=1)
df21

,CASEID,YEAR,AGE,GENDER,RACE,ETHNIC,MARSTAT,EDUC,EMPLOY,DETNLF,...,BARBFLG,SEDHPFLG,INHFLG,OTCFLG,OTHERFLG,ALCDRUG,DSMCRIT,PSYPROB,HLTHINS,PRIMPAY
0,1,2011,10,2,5,5,2,4,1,-9,...,0,0,0,0,0,3,-9,-9,-9,-9
1,2,2011,7,2,5,5,3,3,1,-9,...,0,0,0,0,0,2,7,2,2,4
2,3,2011,6,1,5,5,1,3,1,-9,...,0,0,0,0,0,2,5,2,-9,-9
3,4,2011,9,1,4,5,3,3,3,-9,...,0,0,0,0,0,2,6,2,-9,-9
4,5,2011,8,1,21,5,1,3,3,-9,...,0,0,0,0,0,3,5,1,-9,5
5,6,2011,11,2,4,5,1,2,3,-9,...,0,0,0,0,0,2,6,2,4,-9
6,7,2011,10,1,4,5,1,3,4,-9,...,0,0,0,0,0,3,4,2,-9,-9
7,8,2011,9,1,5,5,3,4,3,-9,...,0,0,0,0,0,3,4,2,-9,-9
8,9,2011,8,1,5,5,1,3,1,-9,...,0,0,0,0,0,3,4,2,-9,-9
9,10,2011,7,1,5,5,2,4,4,6,...,0,0,0,0,0,3,5,2,4,8
10,11,2011,6,2,5,5,1,4,3,-9,...,0,0,0,0,0,2,5,2,-9,-9
11,12,2011,6,2,5,5,4,3,3,-9,...,0,0,0,0,0,2,5,2,-9,5
12,13,2011,5,2,5,5,1,4,1,-9,...,0,0,0,0,0,2,5,1,-9,9
13,14,2011,12,1,5,5,1,3,4,3,...,0,0,0,0,0,3,-9,-9,-9,-9
14,15,2011,6,1,21,5,1,3,4,3,...,0,0,0,0,0,3,4,1,2,4
15,16,2011,8,1,5,5,3,4,1,-9,...,0,0,0,0,0,3,8,2,4,5
16,17,2011,7,2,4,5,1,3,2,-9,...,0,0,0,0,0,2,7,2,2,-9
17,18,2011,8,2,5,5,4,4,4,6,...,0,0,0,0,0,3,5,2,-9,-9
18,19,2011,7,1,4,5,1,4,3,-9,...,0,0,0,0,0,1,9,2,-9,-9
19,20,2011,3,1,20,6,1,2,4,-9,...,0,0,0,0,0,2,7,2,-9,-9
20,21,2011,10,1,4,5,2,5,3,-9,...,0,0,0,0,0,3,2,2,4,-9
21,22,2011,7,1,5,5,1,4,3,-9,...,0,0,0,0,0,2,8,2,-9,5
22,23,2011,8,2,2,5,1,3,1,-9,...,0,0,0,0,0,1,4,1,3,5
23,24,2011,5,1,5,5,4,1,3,-9,...,0,0,0,0,0,2,-9,2,4,5
24,25,2011,7,2,5,5,1,4,1,-9,...,0,0,0,0,0,2,7,1,4,1
25,26,2011,7,2,4,5,1,2,3,-9,...,0,0,0,0,0,2,5,2,-9,-9
26,27,2011,11,1,5,5,2,3,4,3,...,0,0,0,0,0,1,4,2,-9,-9
27,28,2011,5,2,21,5,1,3,3,-9,...,0,0,0,0,0,3,-9,1,4,8
28,29,2011,10,2,5,5,4,3,2,-9,...,0,0,0,0,0,2,6,2,-9,-9
29,30,2011,12,1,4,5,1,4,3,-9,...,0,0,0,0,0,1,4,2,-9,-9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1928645,1928646,2011,11,2,5,5,1,4,3,-9,...,0,0,0,0,0,1,4,-9,4,1
1928646,1928647,2011,12,1,5,5,4,3,3,-9,...,0,0,0,0,0,1,3,2,4,9
1928647,1928648,2011,6,1,5,2,1,2,2,-9,...,0,0,0,0,0,2,-9,2,1,1
1928648,1928649,2011,3,1,5,2,-9,2,4,-9,...,0,0,0,0,0,2,-9,2,-9,-9
1928649,1928650,2011,7,1,5,5,1,5,3,-9,...,0,0,0,0,1,3,2,1,4,9
1928650,1928651,2011,10,1,5,5,-9,3,2,-9,...,0,0,0,0,0,2,-9,2,-9,-9
1928651,1928652,2011,5,1,5,5,-9,2,3,-9,...,0,0,0,0,0,2,-9,2,-9,-9
1928652,1928653,2011,12,1,5,5,4,2,3,-9,...,0,0,0,0,1,3,3,2,4,9
1928653,1928654,2011,10,1,5,5,-9,4,3,-9,...,0,0,0,0,0,2,-9,2,-9,-9
1928654,1928655,2011,9,1,5,5,2,4,1,-9,...,0,0,0,0,0,3,-9,-9,4,-9
1928655,1928656,2011,12,1,5,5,4,5,4,5,...,0,0,0,0,0,3,4,1,4,5
1928656,1928657,2011,8,1,5,5,4,5,1,-9,...,0,0,0,0,0,1,3,2,4,1
1928657,1928658,2011,12,1,5,5,-9,1,3,-9,...,0,0,0,0,0,3,-9,2,-9,-9
1928658,1928659,2011,6,1,5,5,-9,3,1,-9,...,0,0,0,0,0,2,-9,2,-9,-9
1928659,1928660,2011,8,1,2,5,3,2,3,-9,...,0,0,0,0,0,3,-9,-9,4,-9
1928660,1928661,2011,6,2,5,5,1,3,3,-9,...,0,0,0,0,0,3,-9,1,4,1
1928661,1928662,2011,7,2,20,2,-9,2,3,-9,...,0,0,0,0,0,1,-9,2,-9,-9
1928662,1928663,2011,3,1,5,5,1,2,4,2,...,0,0,0,0,0,3,13,2,4,9
1928663,1928664,2011,11,1,5,5,4,3,3,-9,...,0,0,0,0,0,2,5,2,4,5
1928664,1928665,2011,7,2,4,5,-9,2,3,-9,...,0,0,0,0,0,1,-9,2,-9,-9
1928665,1928666,2011,10,1,2,5,-9,4,3,-9,...,0,0,0,0,0,2,-9,2,-9,-9
1928666,1928667,2011,10,1,20,2,-9,3,4,-9,...,0,0,0,0,0,1,-9,2,-9,-9
1928667,1928668,2011,12,1,4,5,-9,4,4,-9,...,0,0,0,0,0,2,-9,2,-9,-9
1928668,1928669,2011,12,2,20,5,-9,2,4,-9,...,0,0,0,0,0,1,-9,2,-9,-9
1928669,1928670,2011,6,2,-9,6,1,2,3,-9,...,0,0,0,0,0,3,8,1,4,-9
1928670,1928671,2011,9,1,3,5,1,4,1,-9,...,0,0,0,0,0,1,-9,2,-9,-9
1928671,1928672,2011,5,1,5,5,1,4,2,-9,...,0,0,0,0,0,1,-9,-9,4,-9
1928672,1928673,2011,9,1,5,5,2,3,3,-9,...,0,0,0,0,0,1,-9,-9,3,-9
1928673,1928674,2011,7,1,5,2,-9,1,4,-9,...,0,0,0,0,0,2,-9,2,-9,-9
1928674,1928675,2011,8,1,4,5,-9,2,3,-9,...,0,0,0,0,0,2,-9,2,-9,-9

In [8]:
#Drop unnecessary columns
df2 = df21.drop(df21.columns[[0, 1, 5, 9, 10, 11, 14, 15, 16, 18, 19, 20, 21, 22, 23, 26, 30, 31, 32, 34, 35, 36, 
                      38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 60, 61]], axis=1)
df2

,AGE,GENDER,RACE,MARSTAT,EDUC,EMPLOY,LIVARAG,PRIMINC,REGION,NOPRIOR,SUB1,FREQ1,FRSTUSE1,SUB2,SUB3,NUMSUBS,ALCDRUG,PSYPROB
0,10,2,5,2,4,1,3,1,2,0,7,4,5,2,1,2,3,-9
1,7,2,5,3,3,1,3,1,2,0,3,2,5,1,-9,1,2,2
2,6,1,5,1,3,1,3,-9,2,0,7,5,1,1,1,1,2,2
3,9,1,4,3,3,3,1,-9,2,1,3,4,4,1,1,1,2,2
4,8,1,21,1,3,3,3,21,2,2,5,5,4,2,1,2,3,1
5,11,2,4,1,2,3,2,2,2,3,3,1,8,1,-9,1,2,2
6,10,1,4,1,3,4,1,-9,2,0,2,5,4,3,1,2,3,2
7,9,1,5,3,4,3,1,-9,2,2,2,1,4,7,4,3,3,2
8,8,1,5,1,3,1,3,-9,2,2,2,4,3,4,1,2,3,2
9,7,1,5,2,4,4,3,21,2,2,5,5,3,7,2,3,3,2
10,6,2,5,1,4,3,3,-9,2,5,5,5,6,1,1,1,2,2
11,6,2,5,4,3,3,3,21,2,1,5,1,6,7,1,2,2,2
12,5,2,5,1,4,1,3,1,2,1,7,5,3,3,5,3,2,1
13,12,1,5,1,3,4,1,20,2,5,3,1,7,4,2,3,3,-9
14,6,1,21,1,3,4,3,3,2,3,4,2,2,2,10,3,3,1
15,8,1,5,3,4,1,3,1,2,2,11,1,4,2,4,3,3,2
16,7,2,4,1,3,2,3,-9,2,1,4,1,-9,7,1,2,2,2
17,8,2,5,4,4,4,2,-9,2,4,5,5,7,2,3,3,3,2
18,7,1,4,1,4,3,3,-9,2,0,2,3,5,1,1,1,1,2
19,3,1,20,1,2,4,2,-9,2,2,4,4,3,1,1,1,2,2
20,10,1,4,2,5,3,2,21,2,3,3,5,6,2,1,2,3,2
21,7,1,5,1,4,3,3,21,2,3,3,5,6,9,4,3,2,2
22,8,2,2,1,3,1,3,1,2,3,2,3,3,1,1,1,1,1
23,5,1,5,4,1,3,3,21,2,2,4,1,1,10,1,2,2,2
24,7,2,5,1,4,1,1,1,2,1,4,3,2,1,1,1,2,1
25,7,2,4,1,2,3,3,-9,2,0,7,5,4,1,1,1,2,2
26,11,1,5,2,3,4,3,-9,2,0,2,5,6,1,1,1,1,2
27,5,2,21,1,3,3,1,2,2,0,4,1,3,2,1,2,3,1
28,10,2,5,4,3,2,3,-9,2,1,3,4,8,3,1,2,2,2
29,12,1,4,1,4,3,3,-9,2,1,2,5,3,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1928645,11,2,5,1,4,3,3,21,4,0,2,4,3,1,1,1,1,-9
1928646,12,1,5,4,3,3,3,21,4,5,2,5,3,1,1,1,1,2
1928647,6,1,5,1,2,2,3,1,4,0,4,1,2,1,1,1,2,2
1928648,3,1,5,-9,2,4,3,-9,4,0,4,1,3,1,-9,1,2,2
1928649,7,1,5,1,5,3,3,20,4,5,5,5,5,2,20,3,3,1
1928650,10,1,5,-9,3,2,3,-9,4,0,10,5,3,4,-9,2,2,2
1928651,5,1,5,-9,2,3,3,-9,4,3,5,5,3,1,-9,1,2,2
1928652,12,1,5,4,2,3,1,21,4,5,2,4,3,20,1,2,3,2
1928653,10,1,5,-9,4,3,3,-9,4,0,10,1,5,4,-9,2,2,2
1928654,9,1,5,2,4,1,3,1,4,0,2,5,3,4,1,2,3,-9
1928655,12,1,5,4,5,4,2,21,4,5,2,1,4,4,3,3,3,1
1928656,8,1,5,4,5,1,3,1,4,5,2,5,3,1,1,1,1,2
1928657,12,1,5,-9,1,3,2,-9,4,2,2,1,2,10,-9,2,3,2
1928658,6,1,5,-9,3,1,3,-9,4,0,5,5,5,7,-9,2,2,2
1928659,8,1,2,3,2,3,3,21,4,0,2,5,1,4,1,2,3,-9
1928660,6,2,5,1,3,3,3,20,4,2,2,1,3,4,3,3,3,1
1928661,7,2,20,-9,2,3,1,-9,4,1,2,1,3,1,-9,1,1,2
1928662,3,1,5,1,2,4,2,1,4,1,4,2,1,2,9,3,3,2
1928663,11,1,5,4,3,3,2,20,4,3,10,5,8,5,4,3,2,2
1928664,7,2,4,-9,2,3,2,-9,4,0,2,1,4,1,-9,1,1,2
1928665,10,1,2,-9,4,3,1,-9,4,3,10,4,7,4,-9,2,2,2
1928666,10,1,20,-9,3,4,1,-9,4,0,2,3,2,1,-9,1,1,2
1928667,12,1,4,-9,4,4,1,-9,4,5,5,3,5,3,-9,2,2,2
1928668,12,2,20,-9,2,4,1,-9,4,5,2,1,1,1,-9,1,1,2
1928669,6,2,-9,1,2,3,2,-9,4,1,2,1,4,10,1,2,3,1
1928670,9,1,3,1,4,1,2,-9,4,1,2,2,4,1,1,1,1,2
1928671,5,1,5,1,4,2,3,1,4,0,2,3,3,1,1,1,1,-9
1928672,9,1,5,2,3,3,3,2,4,0,2,5,2,1,1,1,1,-9
1928673,7,1,5,-9,1,4,2,-9,4,1,10,1,5,1,-9,1,2,2
1928674,8,1,4,-9,2,3,2,-9,4,1,10,2,4,4,-9,2,2,2

In [9]:
#Get column names of the new dataset (df2)
#Column_names = df2.columns.values
for i in enumerate (df2.columns):
    print (i)

(0, 'AGE')
(1, 'GENDER')
(2, 'RACE')
(3, 'MARSTAT')
(4, 'EDUC')
(5, 'EMPLOY')
(6, 'LIVARAG')
(7, 'PRIMINC')
(8, 'REGION')
(9, 'NOPRIOR')
(10, 'SUB1')
(11, 'FREQ1')
(12, 'FRSTUSE1')
(13, 'SUB2')
(14, 'SUB3')
(15, 'NUMSUBS')
(16, 'ALCDRUG')
(17, 'PSYPROB')

In [10]:
#Count unique values of each column in df2
print ('AGE',  df1.AGE.nunique())
print ('GENDER', df1.GENDER.nunique())
print ('RACE', df1.RACE.nunique())
print ('MARSTAT', df1.MARSTAT.nunique())
print ('EDUC', df1.EDUC.nunique())
print ('EMPLOY', df1.EMPLOY.nunique())
print ('LIVARAG', df1.LIVARAG.nunique())
print ('PRIMINC', df1.PRIMINC.nunique())
print ('REGION', df1.REGION.nunique())
print ('NOPRIOR', df1.NOPRIOR.nunique())
print ('SUB1', df1.SUB1.nunique())
print ('FREQ1', df1.FREQ1.nunique())
print ('FRSTUSE1', df2.FRSTUSE1.nunique())
print ('SUB2', df1.SUB2.nunique())
print ('SUB3', df1.SUB3.nunique())
print ('NUMSUBS', df1.NUMSUBS.nunique())
print ('ALCDRUG', df1.ALCDRUG.nunique())
print ('PSYPROB', df1.PSYPROB.nunique())

AGE 11
GENDER 3
RACE 10
MARSTAT 5
EDUC 6
EMPLOY 5
LIVARAG 4
PRIMINC 6
REGION 5
NOPRIOR 7
SUB1 20
FREQ1 6
FRSTUSE1 13
SUB2 20
SUB3 20
NUMSUBS 4
ALCDRUG 4
PSYPROB 3

In [13]:
df2.AGE.unique()

array([ 7, 12,  5,  6,  9, 10, 11,  4,  3,  8,  2])

In [14]:
df2.GENDER.unique()

array([ 2,  1, -9])

In [15]:
df2.MARSTAT.unique()

array([ 4,  2,  1,  3, -9])

In [16]:
df2.EDUC.unique()

array([ 3,  5,  4,  2, -9,  1])

In [17]:
df2.EMPLOY.unique()

array([ 3,  1,  4,  2, -9])

In [18]:
df2.LIVARAG.unique()

array([ 3,  1,  2, -9])

In [19]:
df2.PRIMINC.unique()

array([21,  1,  3, -9,  2, 20])

In [20]:
df2.REGION.unique()

array([2, 4, 1, 3, 0])

In [21]:
df2.NOPRIOR.unique()

array([ 2,  0,  5,  1,  4, -9,  3])

In [22]:
df2.FREQ1.unique()

array([ 2,  5,  4,  1,  3, -9])

In [23]:
df2.NUMSUBS.unique()

array([3, 2, 1, 0])

In [24]:
df2.ALCDRUG.unique()

array([3, 1, 2, 0])

In [25]:
df2.PSYPROB.unique()

array([ 1, -9,  2])

In [26]:
#List unique values of columns in df2
df2.FRSTUSE1.unique()

array([ 2,  5,  4,  3,  6,  1,  7,  8,  9, 11, -9, 10, 12])

In [11]:
# df2['FRSTUSE1'].replace(to_replace=['11 AND UNDER'], value=['14 AND UNDER'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['12-14'], value=['14 AND UNDER'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['15-17'], value=['15-24'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['18-20'], value=['15-24'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['21-24'], value=['15-24'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['25-29'], value=['25-34'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['30-34'], value=['25-34'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['35-39'], value=['35-44'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['40-44'], value=['35-44'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['45-49'], value=['45 AND OVER'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['50-54'], value=['45 AND OVER'], inplace=True)
# df2['FRSTUSE1'].replace(to_replace=['55 AND OVER'], value=['45 AND OVER'], inplace=True)
# df2.FRSTUSE1.unique()

TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'

In [27]:
df2.AGE.unique()

array([ 7, 12,  5,  6,  9, 10, 11,  4,  3,  8,  2])

In [12]:
df2['AGE'].replace(to_replace=[2], value=['17 AND UNDER'], inplace=True)
df2['AGE'].replace(to_replace=[3], value=['17 AND UNDER'], inplace=True)
df2['AGE'].replace(to_replace=[4], value=['18-24'], inplace=True)
df2['AGE'].replace(to_replace=[5], value=['18-24'], inplace=True)
df2['AGE'].replace(to_replace=[6], value=['25-34'], inplace=True)
df2['AGE'].replace(to_replace=[7], value=['25-34'], inplace=True)
df2['AGE'].replace(to_replace=[8], value=['35-44'], inplace=True)
df2['AGE'].replace(to_replace=[9], value=['35-44'], inplace=True)
df2['AGE'].replace(to_replace=[10], value=['45 AND OVER'], inplace=True)
df2['AGE'].replace(to_replace=[11], value=['45 AND OVER'], inplace=True)
df2['AGE'].replace(to_replace=[12], value=['45 AND OVER'], inplace=True)
df2.AGE.unique()

array(['45 AND OVER', '25-34', '35-44', '18-24', '17 AND UNDER'], dtype=object)

In [13]:
df2.RACE.unique()

array([ 5,  4, 21, 20,  2, -9, 23, 13,  1,  3])

In [14]:
df2['RACE'].replace(to_replace=[20], value=['OTHER'], inplace=True)
df2['RACE'].replace(to_replace=[21], value=['OTHER'], inplace=True)
df2['RACE'].replace(to_replace=[23], value=['OTHER'], inplace=True)
df2['RACE'].replace(to_replace=[3], value=['OTHER'], inplace=True)
df2.RACE.unique()

array([5, 4, 'OTHER', 2, -9, 13, 1], dtype=object)

In [15]:
df2.SUB1.unique()

array([ 7,  3,  5,  2,  4, 11, 10,  1, 20,  9, 13, 16,  6, 18, -9, 17,  8,
       12, 15, 14])

In [16]:
df2['SUB1'].replace(to_replace=[2], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[3], value=['HERO/MARI/COC'], inplace=True)
df2['SUB1'].replace(to_replace=[4], value=['HERO/MARI/COC'], inplace=True)
df2['SUB1'].replace(to_replace=[5], value=['HERO/MARI/COC'], inplace=True)
df2['SUB1'].replace(to_replace=[6], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[7], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[8], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[9], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[10], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[1], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[11], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[12], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[13], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[14], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[15], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[16], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[17], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[18], value=['OTHER'], inplace=True)
df2['SUB1'].replace(to_replace=[20], value=['OTHER'], inplace=True)
df2.SUB1.unique()

array(['OTHER', 'HERO/MARI/COC', -9], dtype=object)

In [17]:
#Merging Firstuse categories
df2['FRSTUSE1'].replace(to_replace=[1], value=['14 AND UNDER'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[2], value=['14 AND UNDER'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[3], value=['15-24'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[4], value=['15-24'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[5], value=['15-24'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[6], value=['25-34'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[7], value=['25-34'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[8], value=['35-44'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[9], value=['35-44'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[10], value=['45 AND OVER'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[11], value=['45 AND OVER'], inplace=True)
df2['FRSTUSE1'].replace(to_replace=[12], value=['45 AND OVER'], inplace=True)
df2.FRSTUSE1.unique()

array(['15-24', '14 AND UNDER', '35-44', '25-34', -9, '45 AND OVER'], dtype=object)

In [18]:
df3 = df2[df2.SUB1 != -9]
len(df3['SUB1'])

1922525

In [19]:
df3.SUB1.unique()

array(['OTHER', 'HERO/MARI/COC'], dtype=object)

In [20]:
df3.SUB2.unique()

array([ 2,  1,  3,  7,  4,  9, 10, 15, 17,  6, 11,  5, 20, 13, 12, -9, 16,
       14, 18,  8])

In [21]:
df3['SUB2'].replace(to_replace=[7], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[20], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[8], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[1], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[6], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[11], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[16], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[14], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[17], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[12], value=['OTHER'], inplace=True)
df3['SUB2'].replace(to_replace=[9], value=['OTHER'], inplace=True)
df3.SUB2.unique()

/Users/nuthakki/anaconda/lib/python3.6/site-packages/pandas/core/generic.py:4619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

array([2, 'OTHER', 3, 4, 10, 15, 5, 13, -9, 18], dtype=object)

In [22]:
df3['SUB3'].replace(to_replace=[7], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[20], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[8], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[1], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[6], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[11], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[16], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[14], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[17], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[12], value=['OTHER'], inplace=True)
df3['SUB3'].replace(to_replace=[9], value=['OTHER'], inplace=True)
df3.SUB3.unique()

/Users/nuthakki/anaconda/lib/python3.6/site-packages/pandas/core/generic.py:4619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

array(['OTHER', -9, 4, 2, 5, 10, 3, 18, 13, 15], dtype=object)

In [23]:
df3.columns.values

array(['AGE', 'GENDER', 'RACE', 'MARSTAT', 'EDUC', 'EMPLOY', 'LIVARAG',
       'PRIMINC', 'REGION', 'NOPRIOR', 'SUB1', 'FREQ1', 'FRSTUSE1', 'SUB2',
       'SUB3', 'NUMSUBS', 'ALCDRUG', 'PSYPROB'], dtype=object)

In [24]:
df4 = pd.get_dummies(df3, columns = ['AGE', 'GENDER', 'RACE', 'MARSTAT', 'EDUC', 'EMPLOY', 'LIVARAG',
       'PRIMINC', 'REGION', 'NOPRIOR', 'SUB1', 'FREQ1', 'FRSTUSE1', 'SUB2',
       'SUB3', 'NUMSUBS', 'ALCDRUG', 'PSYPROB'])

In [25]:
df4.columns

Index(['AGE_17 AND UNDER', 'AGE_18-24', 'AGE_25-34', 'AGE_35-44',
       'AGE_45 AND OVER', 'GENDER_-9', 'GENDER_1', 'GENDER_2', 'RACE_-9',
       'RACE_1', 'RACE_2', 'RACE_4', 'RACE_5', 'RACE_13', 'RACE_OTHER',
       'MARSTAT_-9', 'MARSTAT_1', 'MARSTAT_2', 'MARSTAT_3', 'MARSTAT_4',
       'EDUC_-9', 'EDUC_1', 'EDUC_2', 'EDUC_3', 'EDUC_4', 'EDUC_5',
       'EMPLOY_-9', 'EMPLOY_1', 'EMPLOY_2', 'EMPLOY_3', 'EMPLOY_4',
       'LIVARAG_-9', 'LIVARAG_1', 'LIVARAG_2', 'LIVARAG_3', 'PRIMINC_-9',
       'PRIMINC_1', 'PRIMINC_2', 'PRIMINC_3', 'PRIMINC_20', 'PRIMINC_21',
       'REGION_0', 'REGION_1', 'REGION_2', 'REGION_3', 'REGION_4',
       'NOPRIOR_-9', 'NOPRIOR_0', 'NOPRIOR_1', 'NOPRIOR_2', 'NOPRIOR_3',
       'NOPRIOR_4', 'NOPRIOR_5', 'SUB1_HERO/MARI/COC', 'SUB1_OTHER',
       'FREQ1_-9', 'FREQ1_1', 'FREQ1_2', 'FREQ1_3', 'FREQ1_4', 'FREQ1_5',
       'FRSTUSE1_-9', 'FRSTUSE1_14 AND UNDER', 'FRSTUSE1_15-24',
       'FRSTUSE1_25-34', 'FRSTUSE1_35-44', 'FRSTUSE1_45 AND OVER', 'SUB2_-9',
       'SUB2_2', 'SUB2_3', 'SUB2_4', 'SUB2_5', 'SUB2_10', 'SUB2_13', 'SUB2_15',
       'SUB2_18', 'SUB2_OTHER', 'SUB3_-9', 'SUB3_2', 'SUB3_3', 'SUB3_4',
       'SUB3_5', 'SUB3_10', 'SUB3_13', 'SUB3_15', 'SUB3_18', 'SUB3_OTHER',
       'NUMSUBS_0', 'NUMSUBS_1', 'NUMSUBS_2', 'NUMSUBS_3', 'ALCDRUG_0',
       'ALCDRUG_1', 'ALCDRUG_2', 'ALCDRUG_3', 'PSYPROB_-9', 'PSYPROB_1',
       'PSYPROB_2'],
      dtype='object')

In [26]:
for i in enumerate(df4.columns):
    print(i)

(0, 'AGE_17 AND UNDER')
(1, 'AGE_18-24')
(2, 'AGE_25-34')
(3, 'AGE_35-44')
(4, 'AGE_45 AND OVER')
(5, 'GENDER_-9')
(6, 'GENDER_1')
(7, 'GENDER_2')
(8, 'RACE_-9')
(9, 'RACE_1')
(10, 'RACE_2')
(11, 'RACE_4')
(12, 'RACE_5')
(13, 'RACE_13')
(14, 'RACE_OTHER')
(15, 'MARSTAT_-9')
(16, 'MARSTAT_1')
(17, 'MARSTAT_2')
(18, 'MARSTAT_3')
(19, 'MARSTAT_4')
(20, 'EDUC_-9')
(21, 'EDUC_1')
(22, 'EDUC_2')
(23, 'EDUC_3')
(24, 'EDUC_4')
(25, 'EDUC_5')
(26, 'EMPLOY_-9')
(27, 'EMPLOY_1')
(28, 'EMPLOY_2')
(29, 'EMPLOY_3')
(30, 'EMPLOY_4')
(31, 'LIVARAG_-9')
(32, 'LIVARAG_1')
(33, 'LIVARAG_2')
(34, 'LIVARAG_3')
(35, 'PRIMINC_-9')
(36, 'PRIMINC_1')
(37, 'PRIMINC_2')
(38, 'PRIMINC_3')
(39, 'PRIMINC_20')
(40, 'PRIMINC_21')
(41, 'REGION_0')
(42, 'REGION_1')
(43, 'REGION_2')
(44, 'REGION_3')
(45, 'REGION_4')
(46, 'NOPRIOR_-9')
(47, 'NOPRIOR_0')
(48, 'NOPRIOR_1')
(49, 'NOPRIOR_2')
(50, 'NOPRIOR_3')
(51, 'NOPRIOR_4')
(52, 'NOPRIOR_5')
(53, 'SUB1_HERO/MARI/COC')
(54, 'SUB1_OTHER')
(55, 'FREQ1_-9')
(56, 'FREQ1_1')
(57, 'FREQ1_2')
(58, 'FREQ1_3')
(59, 'FREQ1_4')
(60, 'FREQ1_5')
(61, 'FRSTUSE1_-9')
(62, 'FRSTUSE1_14 AND UNDER')
(63, 'FRSTUSE1_15-24')
(64, 'FRSTUSE1_25-34')
(65, 'FRSTUSE1_35-44')
(66, 'FRSTUSE1_45 AND OVER')
(67, 'SUB2_-9')
(68, 'SUB2_2')
(69, 'SUB2_3')
(70, 'SUB2_4')
(71, 'SUB2_5')
(72, 'SUB2_10')
(73, 'SUB2_13')
(74, 'SUB2_15')
(75, 'SUB2_18')
(76, 'SUB2_OTHER')
(77, 'SUB3_-9')
(78, 'SUB3_2')
(79, 'SUB3_3')
(80, 'SUB3_4')
(81, 'SUB3_5')
(82, 'SUB3_10')
(83, 'SUB3_13')
(84, 'SUB3_15')
(85, 'SUB3_18')
(86, 'SUB3_OTHER')
(87, 'NUMSUBS_0')
(88, 'NUMSUBS_1')
(89, 'NUMSUBS_2')
(90, 'NUMSUBS_3')
(91, 'ALCDRUG_0')
(92, 'ALCDRUG_1')
(93, 'ALCDRUG_2')
(94, 'ALCDRUG_3')
(95, 'PSYPROB_-9')
(96, 'PSYPROB_1')
(97, 'PSYPROB_2')

In [27]:
#Take necessary columns
x = df4.ix[:,(1,2,3,4,7,11,12,13,14,17,19,41,43,44,45,57,58,59,60,61,62,65,66,68,73,73,69,70,71,
                       75,78,80,81,85,88,87,91,92,93,94)].values
y = df4.ix[:,53].values
print(y)

/Users/nuthakki/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

[0 1 0 ..., 0 0 0]

In [28]:
df6 = df4.ix[:,(1,2,3,4,7,11,12,13,14,17,19,41,43,44,45,57,58,59,60,61,62,65,66,68,73,73,69,70,71,
                       75,78,80,81,85,88,87,91,92,93,94,53)]
len(df6)

1922525

In [29]:
df6[:10000]

,AGE_18-24,AGE_25-34,AGE_35-44,AGE_45 AND OVER,GENDER_2,RACE_4,RACE_5,RACE_13,RACE_OTHER,MARSTAT_2,...,SUB3_4,SUB3_5,SUB3_18,NUMSUBS_1,NUMSUBS_0,ALCDRUG_0,ALCDRUG_1,ALCDRUG_2,ALCDRUG_3,SUB1_HERO/MARI/COC
0,0,0,0,1,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1,0,1,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,1
2,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,0,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1
4,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1
5,0,0,0,1,1,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1
6,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
7,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
8,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,0,1,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1
10,0,1,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,1
11,0,1,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
12,1,0,0,0,1,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
13,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
14,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1
15,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
16,0,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
17,0,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
18,0,1,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
19,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,1
20,0,0,0,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,1
21,0,1,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,1
22,0,0,1,0,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
23,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
24,0,1,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,1
25,0,1,0,0,1,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
26,0,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,0,1,0,0,0
27,1,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1
28,0,0,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
29,0,0,0,1,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,0,1,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,1
9986,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
9987,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
9988,1,0,0,0,0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
9989,1,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1
9990,0,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
9991,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
9992,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1
9993,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
9994,0,1,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
9995,0,0,0,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
9996,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
9997,0,1,0,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
9998,1,0,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,1
9999,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10000,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
10001,1,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
10002,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10003,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,1,0,0,0,0
10004,0,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10005,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
10006,0,0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
10007,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1
10008,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
10009,0,0,1,0,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
10010,0,1,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
10011,1,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
10012,0,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
10013,0,0,0,1,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
10014,1,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [30]:
df6.to_csv('/Users/nuthakki/Desktop/2011_10000.csv', na_rep='NA')